export const FETCH_HOME_DATA = "FETCH_HOME_DATA";
export const FETCH_TOP_HEADLINES = "FETCH_TOP_HEADLINES";
export const FETCH_TOURISM_DATA = "FETCH_TOURISM_DATA";
export const DRAWER_TOGGLE_CLICK_HANDLER = "DRAWER_TOGGLE_CLICK_HANDLER";
